### ISSUE TITLE
0.1 release check list

### ISSUE THREAD

**Issue by rafalp** [rafalp/misago_docker#61]
### TODO

* [x] Update Misago dependencies to resolve security warnings
* [x] Configure e-mail sending using SMTP
* [x] Restore data from backup
* [x] Clean start on fresh VPS
* [x] Clean start on fresh VPS, using non-root user

**Comment by rafalp** [comment]
Tested everything out and its working \o/
